# Generated by Django 4.2 on 2024-03-01 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='路由名称', max_length=255, unique=True)),
                ('url', models.CharField(db_comment='路由地址', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'DTP_router',
                'db_table_comment': '路由表',
            },
        ),
        migrations.CreateModel(
            name='RouterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='权限名称', max_length=255, unique=True)),
                ('method', models.CharField(db_comment='请求方式', max_length=255)),
                ('router', models.ForeignKey(db_comment='关联路由', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.router')),
            ],
            options={
                'db_table': 'DTP_router_permission',
                'db_table_comment': '路由权限表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='角色名', max_length=255, unique=True)),
                ('router_permission', models.ManyToManyField(db_constraint=False, db_table='DTP_role_router_permission', to='system.routerpermission')),
                ('user', models.ManyToManyField(db_constraint=False, db_table='DTP_user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DTP_role',
                'db_table_comment': '角色表',
            },
        ),
    ]
