# Generated by Django 4.2 on 2024-03-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_menu_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_catalog',
        ),
    ]
