# Generated by Django 4.2 on 2024-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_menu_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(db_constraint=False, db_table='DTP_role_menu_permission', related_name='canUseMenus', to='system.role'),
        ),
    ]
