# Generated by Django 4.2 on 2024-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_menu_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(db_comment='描述信息', null=True),
        ),
    ]
