# Generated by Django 4.2 on 2024-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_role_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='模型名称', max_length=255, unique=True)),
                ('alias', models.CharField(db_comment='模型别称', max_length=255)),
                ('kind', models.CharField(db_comment='模型类别', max_length=255)),
                ('description', models.TextField(db_comment='描述信息', null=True)),
                ('init_params', models.JSONField(db_comment='初始参数', null=True)),
                ('call_url', models.CharField(db_comment='调用地址', max_length=255)),
                ('call_params', models.JSONField(db_comment='调用参数', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='router_permission',
            field=models.ManyToManyField(db_constraint=False, db_table='DTP_role_router_permission', related_name='related_role', to='system.routerpermission'),
        ),
    ]
