# Generated by Django 4.2 on 2024-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_model_alter_role_router_permission'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='model',
            table_comment='模型表',
        ),
        migrations.AddField(
            model_name='model',
            name='roles',
            field=models.ManyToManyField(db_constraint=False, db_table='DTP_role_model_permission', to='system.role'),
        ),
        migrations.AlterModelTable(
            name='model',
            table='DTP_model',
        ),
    ]
