"""权限表重新设计

Revision ID: 11f25f10a9f6
Revises: cf1c66be02ff
Create Date: 2026-01-06 21:29:57.112859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f25f10a9f6'
down_revision: Union[str, Sequence[str], None] = 'cf1c66be02ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rbac_permissions', sa.Column('menu_path', sa.String(length=200), nullable=True, comment='前端菜单路由路径（如 /system/user）'))
    op.add_column('rbac_permissions', sa.Column('menu_name', sa.String(length=50), nullable=True, comment='菜单显示名称（如 用户管理）'))
    op.add_column('rbac_permissions', sa.Column('menu_icon', sa.String(length=50), nullable=True, comment='菜单图标（如 el-icon-user）'))
    op.add_column('rbac_permissions', sa.Column('menu_parent_id', sa.Integer(), nullable=True, comment='父菜单ID（用于构建树形菜单）'))
    op.add_column('rbac_permissions', sa.Column('menu_sort', sa.Integer(), nullable=False, comment='菜单排序号（前端展示顺序）'))
    op.add_column('rbac_permissions', sa.Column('menu_is_visible', sa.Boolean(), nullable=False, comment='是否显示（即使有权限也可隐藏）'))
    op.create_foreign_key(None, 'rbac_permissions', 'rbac_permissions', ['menu_parent_id'], ['id'])
    op.drop_column('rbac_permissions', 'is_visible')
    op.drop_column('rbac_permissions', 'action')
    op.drop_column('rbac_permissions', 'resource')
    op.drop_column('rbac_permissions', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rbac_permissions', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='排序号（菜单顺序）'))
    op.add_column('rbac_permissions', sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='资源标识（如 user / order）'))
    op.add_column('rbac_permissions', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='动作标识（如 create / delete / export）'))
    op.add_column('rbac_permissions', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否在菜单中可见'))
    op.drop_constraint(None, 'rbac_permissions', type_='foreignkey')
    op.drop_column('rbac_permissions', 'menu_is_visible')
    op.drop_column('rbac_permissions', 'menu_sort')
    op.drop_column('rbac_permissions', 'menu_parent_id')
    op.drop_column('rbac_permissions', 'menu_icon')
    op.drop_column('rbac_permissions', 'menu_name')
    op.drop_column('rbac_permissions', 'menu_path')
    # ### end Alembic commands ###
