"""使用外键，且不再使用自定义的中间表

Revision ID: 6cbdba972977
Revises: 
Create Date: 2026-01-06 11:50:11.669040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbdba972977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_departments',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父级部门ID'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='树路径'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['rbac_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表'
    )
    op.create_index(op.f('ix_rbac_departments_path'), 'rbac_departments', ['path'], unique=False)
    op.create_table('rbac_permissions',
    sa.Column('name', sa.String(length=50), nullable=False, comment='权限唯一标识（如 user:create, order:cancel）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='权限描述'),
    sa.Column('type', sa.Enum('menu', 'action', 'api', name='permission_type'), nullable=False, comment='权限类型：menu / action / api'),
    sa.Column('api_path', sa.String(length=200), nullable=True, comment='API 路径（如 /api/users/{id}）'),
    sa.Column('api_method', sa.String(length=10), nullable=True, comment='HTTP 方法（GET/POST/PUT/DELETE）'),
    sa.Column('resource', sa.String(length=50), nullable=True, comment='资源标识（如 user / order）'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='动作标识（如 create / delete / export）'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否在菜单中可见'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序号（菜单顺序）'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表'
    )
    op.create_index('idx_permission_api', 'rbac_permissions', ['api_path', 'api_method'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_permission_name', 'rbac_permissions', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('rbac_roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_index('idx_roles_name', 'rbac_roles', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('rbac_users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_username', 'rbac_users', ['username'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_department',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['rbac_departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user_department')
    op.drop_table('role_permission')
    op.drop_index('idx_users_username', table_name='rbac_users', postgresql_where='deleted_at IS NULL')
    op.drop_table('rbac_users')
    op.drop_index('idx_roles_name', table_name='rbac_roles', postgresql_where='deleted_at IS NULL')
    op.drop_table('rbac_roles')
    op.drop_index('idx_permission_name', table_name='rbac_permissions', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_permission_api', table_name='rbac_permissions', postgresql_where='deleted_at IS NULL')
    op.drop_table('rbac_permissions')
    op.drop_index(op.f('ix_rbac_departments_path'), table_name='rbac_departments')
    op.drop_table('rbac_departments')
    # ### end Alembic commands ###
