"""权限表重设计，拆分菜单表

Revision ID: 8b8b7157f5c5
Revises: 11f25f10a9f6
Create Date: 2026-01-06 21:53:37.513234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8b7157f5c5'
down_revision: Union[str, Sequence[str], None] = '11f25f10a9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_menus',
    sa.Column('code', sa.String(length=50), nullable=False, comment='菜单唯一标识'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='菜单显示名称'),
    sa.Column('is_directory', sa.Boolean(), nullable=False, comment='是否是目录（目录下可包含子菜单）'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='前端菜单路由路径（如 /system/user）'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标（如 el-icon-user）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='菜单排序号（前端展示顺序）'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否显示（即使有权限也可隐藏）'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单ID（用于构建树形菜单）'),
    sa.Column('permission_id', sa.Integer(), nullable=True, comment='关联权限ID（为空代表是公共菜单）,directory类型菜单无需关联权限'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['rbac_menus.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_index('idx_menu_code', 'rbac_menus', ['code'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_menu_path', 'rbac_menus', ['path'], unique=True, postgresql_where='deleted_at IS NULL')
    op.drop_constraint(op.f('rbac_permissions_menu_parent_id_fkey'), 'rbac_permissions', type_='foreignkey')
    op.drop_column('rbac_permissions', 'menu_sort')
    op.drop_column('rbac_permissions', 'menu_icon')
    op.drop_column('rbac_permissions', 'menu_path')
    op.drop_column('rbac_permissions', 'menu_is_visible')
    op.drop_column('rbac_permissions', 'menu_name')
    op.drop_column('rbac_permissions', 'type')
    op.drop_column('rbac_permissions', 'menu_parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rbac_permissions', sa.Column('menu_parent_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='父菜单ID（用于构建树形菜单）'))
    op.add_column('rbac_permissions', sa.Column('type', postgresql.ENUM('menu', 'action', 'api', name='permission_type'), autoincrement=False, nullable=False, comment='权限类型：menu / action / api'))
    op.add_column('rbac_permissions', sa.Column('menu_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='菜单显示名称（如 用户管理）'))
    op.add_column('rbac_permissions', sa.Column('menu_is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否显示（即使有权限也可隐藏）'))
    op.add_column('rbac_permissions', sa.Column('menu_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='前端菜单路由路径（如 /system/user）'))
    op.add_column('rbac_permissions', sa.Column('menu_icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='菜单图标（如 el-icon-user）'))
    op.add_column('rbac_permissions', sa.Column('menu_sort', sa.INTEGER(), autoincrement=False, nullable=False, comment='菜单排序号（前端展示顺序）'))
    op.create_foreign_key(op.f('rbac_permissions_menu_parent_id_fkey'), 'rbac_permissions', 'rbac_permissions', ['menu_parent_id'], ['id'])
    op.drop_index('idx_menu_path', table_name='rbac_menus', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_menu_code', table_name='rbac_menus', postgresql_where='deleted_at IS NULL')
    op.drop_table('rbac_menus')
    # ### end Alembic commands ###
