"""使用外键，且不再使用自定义的中间表

Revision ID: cf1c66be02ff
Revises: 6cbdba972977
Create Date: 2026-01-06 11:51:27.950977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1c66be02ff'
down_revision: Union[str, Sequence[str], None] = '6cbdba972977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('rbac_user_department',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['rbac_departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    op.create_table('rbac_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('role_permission')
    op.drop_table('user_role')
    op.drop_table('user_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_department',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['rbac_departments.id'], name=op.f('user_department_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], name=op.f('user_department_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'department_id', name=op.f('user_department_pkey'))
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name=op.f('user_role_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['rbac_users.id'], name=op.f('user_role_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_role_pkey'))
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], name=op.f('role_permission_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name=op.f('role_permission_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permission_pkey'))
    )
    op.drop_table('rbac_user_role')
    op.drop_table('rbac_user_department')
    op.drop_table('rbac_role_permission')
    # ### end Alembic commands ###
